import type { Metadata } from "next"

import Navbar from "@/components/navbar"
import Footer from "@/components/footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function LocaleLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar />
      <main className="flex-1 px-4 py-8 lg:px-8">{children}</main>
      <Footer />
    </>
  )
}
